#!/usr/bin/env bash

set -e
set -x

function sethostname(){
  export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function config(){
  # disable THP
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag
  # disable mongod upstart service
  echo 'manual' | tee /etc/init/mongod.override
}

function install_nodejs(){
  sudo apt-get update
  sudo apt-get install -y nodejs npm build-essential libssl-dev git nodejs-legacy
  sudo npm install express
}

function install_mongodb(){
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  sudo apt-get update
  sudo apt-get install -y mongodb-org
  sudo service mongod stop
}

function install_mongodb_mtools(){
  sudo apt-get install -y python-dev python-setuptools python-dev gcc python-pip python-dev
  sudo pip install mtools
#python -m pip install mtools
  sudo pip install pymongo
  sudo pip install python-dateutil --upgrade
  sudo pip install pytz --upgrade
  sudo pip install --upgrade psutil
}

function get_repo(){
  cd /home/vagrant/
  git clone https://github.com/scotch-io/node-todo.git
}


sethostname
config
install_mongodb
install_nodejs
install_mongodb_mtools
get_repo

echo DONE
